// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSej-p4gV7b0j8v3SEB4u87FVN6VD82k',
    appId: '1:793685787962:web:6a65c43840132f4998bc03',
    messagingSenderId: '793685787962',
    projectId: 'chat-app-c0cd6',
    authDomain: 'chat-app-c0cd6.firebaseapp.com',
    storageBucket: 'chat-app-c0cd6.firebasestorage.app',
    measurementId: 'G-6S7198RGV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDSy7U5sF5-fe8QCjkoam5itjLiNuCF8',
    appId: '1:793685787962:android:4890032763f6393b98bc03',
    messagingSenderId: '793685787962',
    projectId: 'chat-app-c0cd6',
    storageBucket: 'chat-app-c0cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPw1GjK_dEZRPgJR3M60_VBqC6tEDlus',
    appId: '1:793685787962:ios:54be3eb566ae2d7f98bc03',
    messagingSenderId: '793685787962',
    projectId: 'chat-app-c0cd6',
    storageBucket: 'chat-app-c0cd6.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPw1GjK_dEZRPgJR3M60_VBqC6tEDlus',
    appId: '1:793685787962:ios:54be3eb566ae2d7f98bc03',
    messagingSenderId: '793685787962',
    projectId: 'chat-app-c0cd6',
    storageBucket: 'chat-app-c0cd6.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsSej-p4gV7b0j8v3SEB4u87FVN6VD82k',
    appId: '1:793685787962:web:8b0fd52b7783598598bc03',
    messagingSenderId: '793685787962',
    projectId: 'chat-app-c0cd6',
    authDomain: 'chat-app-c0cd6.firebaseapp.com',
    storageBucket: 'chat-app-c0cd6.firebasestorage.app',
    measurementId: 'G-4G8MSDPFVL',
  );
}
